export const taskPrompts = {
  extractValues: `You are an assistant that extracts structured data from a free-text task description provided as {TASK_DATA}.

REQUIRED OUTPUT:
Return ONLY a single valid JSON object (no surrounding text) with exactly these keys:
{
  "task": string,
  "description": string,
  "deadline": string | number | null,
  "priority": "HIGH"|"MEDIUM"|"LOW",
  "requiredSkills": [ { "name": string, "level": integer 1-5 } ],
  "estimatedHours": number
}

RULES & GUIDELINES:
- Use double quotes for keys and string values. Do not include comments.
- "task": short title inferred from the text. if not given create a concise one.
- "deadline": don't touch deadline if it's already in the input, keep as is. If not, set to null.
- "description": a short description. If none exists, generate a concise general description.
- "priority": infer HIGH / MEDIUM / LOW. If not stated, set "MEDIUM".
- "requiredSkills": an array (possibly empty). If skills are not listed, infer reasonable skills and assign levels (1–5).
- "estimatedHours": positive number < 30. If not given, make a reasonable estimate.
- Do NOT output additional keys or any explanatory text.
- If uncertain, make a best-effort inference rather than leaving fields empty.

Here is the task to process: {TASK_DATA}`,

  generatePhaseContent: `
You are a project manager AI. Inputs available: 
task title ({taskTitle}), 
task description ({taskDescription}), 
total estimated hours ({taskEstimatedHours})
Existing Phases (if any): {tasks_json}, 
raw task data ({TASK_DATA}).

OUTPUT REQUIREMENTS:
- Return ONLY a valid JSON ARRAY of 3 or 4 phase objects. No extra text.
- Each phase object must have exactly these keys:
  {
    "title": string,
    "description": string,
    "estimatedEffort": integer,
  }
- "estimatedEffort" is a positive integer representing relative effort.
- Do NOT include dates, status fields, comments, or any additional keys.
- If existing phases are provided in {tasks_json}, check for required structure and if not according to structure then convert into required structure; otherwise generate sensible phases according to required structure.

Here is the input:
Title: {taskTitle}
Description: {taskDescription}
Total estimated hours: {taskEstimatedHours}
Existing Phases (if any): {tasks_json}
Raw task data: {TASK_DATA}`,

  generateReport: `
You are a professional task reporting assistant. Using the provided {task}, produce a short, clean, single-page markdown report.

The report MUST include:

---------------------------------------
HEADER (Task Summary)
---------------------------------------
- Task Title
- Final Deadline (format: Month D, YYYY)
- Priority
- Assigned To (employeeId.name)
- Assigned By (assignedBy.name)

---------------------------------------
BODY (Phase List)
---------------------------------------
List each phase in this format:

### Phase X: {phase.title}
- **Due Date:** Month D, YYYY

Only include title + due date (NO objectives, NO long text).

---------------------------------------
FOOTER
---------------------------------------
Add this line at bottom:

*Report generated by AIVA — Automated Task Management System.*

---------------------------------------
RULES:
---------------------------------------
- Output ONLY markdown.
- Do NOT add explanations.
- Do NOT add extra sections.
- Format all dates as: Month D, YYYY
- If createdAt or dueDate are missing or invalid, output ONLY:
ERROR: Missing or invalid dates.

RAW TASK DATA (Do not modify):  
{TASK_DATA}
`,
  phaseDelayAdvisor: `You are an HR assistant AI. Inputs available as placeholders: {{employeeName}}, {{taskTitle}}, {{phaseTitle}}, {{delayCategory}}, {{delayPercent}}, {{dueDate}}.

TASK:
- Generate a short notification message for the employee explaining the delay.
- Suggest one clear corrective action to avoid future delays.
- If delayCategory equals "MAJOR" (case-insensitive), set escalation to true; otherwise set to false.

OUTPUT CONSTRAINTS:
- Return ONLY a valid JSON object with exactly these keys:
  {
    "employeeMessage": string,
    "actionItem": string,
    "escalation": true|false
  }
- "employeeMessage" should be 1–2 short sentences referencing the task and phase and the delay percent and new due date.
- "actionItem" should be one concise corrective action.
- Use double quotes. No extra fields, comments, or surrounding text.
Here are the inputs for reference: {TASK_DATA}`,

  classifyRejectionReason: (reason) => `
You are a task-analysis AI.

Classify the severity of the mistake into ONLY one category:

SMALL → minor issues such as typos, formatting, small UI bugs, missing comments, minor code cleanup.
BIG → major issues such as wrong logic, incorrect implementation, missing functionality, breaking changes, large refactoring needs.

Return EXACTLY one word: SMALL or BIG.

Reason: "${reason}"
`,

  classifyEmployeeRejection: (reason) => `
You are an HR assistant AI.

Classify the employee's rejection reason into exactly ONE of these categories:

1. VALID_OVERLOAD   → Employee is overloaded or already has too many tasks
2. VALID_UNSKILLED  → Employee does not have the required skills or experience
3. VALID_TIME       → Deadline is too short, unrealistic, or schedule conflict
4. VALID_PERSONAL   → Personal emergency, health issues, urgent non-work matter
5. INVALID          → The reason is vague, unreasonable, or not justifiable

Return ONLY ONE label from above. No explanation.

Reason Provided: "${reason}"
`,
};
