export const taskPrompts = {

  extractValues: `You are an assistant that extracts structured data from a free-text task description provided as {TASK_DATA}.

REQUIRED OUTPUT:
Return ONLY a single valid JSON object (no surrounding text) with exactly these keys:
{
  "task": string,
  "description": string,
  "deadline": string | number | null,
  "priority": "HIGH"|"MEDIUM"|"LOW",
  "requiredSkills": [ { "name": string, "level": integer 1-5 } ],
  "estimatedHours": number
}

RULES & GUIDELINES:
- Use double quotes for keys and string values. Do not include comments.
- "task": short title inferred from the text. if not given create a concise one.
- "deadline": don't touch deadline if it's already in the input, keep as is. If not, set to null.
- "description": a short description. If none exists, generate a concise general description.
- "priority": infer HIGH / MEDIUM / LOW. If not stated, set "MEDIUM".
- "requiredSkills": an array (possibly empty). If skills are not listed, infer reasonable skills and assign levels (1–5).
- "estimatedHours": positive number < 30. If not given, make a reasonable estimate.
- Do NOT output additional keys or any explanatory text.
- If uncertain, make a best-effort inference rather than leaving fields empty.

Here is the task to process: {TASK_DATA}`,

generatePhaseContent: `
You are a project manager AI. Inputs available: 
task title ({taskTitle}), 
task description ({taskDescription}), 
total estimated hours ({taskEstimatedHours})
Existing Phases (if any): {tasks_json}, 
raw task data ({TASK_DATA}).

OUTPUT REQUIREMENTS:
- Return ONLY a valid JSON ARRAY of 3 or 4 phase objects. No extra text.
- Each phase object must have exactly these keys:
  {
    "title": string,
    "description": string,
    "estimatedEffort": integer,
  }
- "estimatedEffort" is a positive integer representing relative effort.
- Do NOT include dates, status fields, comments, or any additional keys.
- If existing phases are provided in {tasks_json}, check for required structure and if not according to structure then convert into required structure; otherwise generate sensible phases according to required structure.

Here is the input:
Title: {taskTitle}
Description: {taskDescription}
Total estimated hours: {taskEstimatedHours}
Existing Phases (if any): {tasks_json}
Raw task data: {TASK_DATA}`,

  generateReport: `You are an expert Project Management Assistant. Input fields available within {task} and raw {TASK_DATA}: title, description, dueDate (final deadline), priority, employeeId.name, assignedBy.name, createdAt (report generation date), requiredSkills.

TASK:
1. Generate 3–5 logical phases for the project and a one-sentence objective per phase.
2. Calculate an estimated due date for each phase by proportionally dividing the time between createdAt and dueDate. Allocate more time to phases with higher complexity. Ensure the final phase's due date equals the Overall Deadline exactly.
3. Format all dates as "Month D, YYYY" (e.g., "September 25, 2025").

OUTPUT FORMAT (MUST MATCH EXACTLY; output ONLY this markdown report and nothing else):
# Task Assignment Report

## 1. Project Header

| Field              | Details                               |
| ------------------ | ------------------------------------- |
| **Task Title** | {task.title}                        |
| **Assigned To** | {task.employeeId.name}                     |
| **Assigned By** | {task.assignedBy.name}                  |
| **Priority** | {task.priority}                          |
| **Final Deadline** | **{task.dueDate}** |
| **Report Date** | {task.createdAt}                      |

## 2. Task Overview

(Provide a 2-3 sentence summary of the task's main goal and its importance based on the Task Description.)

## 3. Phase-Wise Breakdown

### **Phase 1: (Generated Phase Title)**
* **Objective:** (one-sentence objective).
* **Estimated Due Date:** (Calculated Due Date)

### **Phase 2: (Generated Phase Title)**
* **Objective:** (one-sentence objective).
* **Estimated Due Date:** (Calculated Due Date)

### **Phase 3: (Generated Phase Title)**
* **Objective:** (one-sentence objective).
* **Estimated Due Date:** (Calculated Due Date)

*(...continue for all generated phases if more than three...)*

## 4. Summary & Next Steps

This structured approach is designed to ensure clarity and timely completion. Please review the plan and confirm your understanding. The first step is to begin with **Phase 1: (Title of the first phase)**. We are confident in your ability to deliver excellent results.

## 5. Report Footer

*Report generated by the Project Management Office.*

ERROR HANDLING:
- If createdAt or dueDate are missing or cannot be parsed as dates, output EXACTLY this single line instead of the report:
ERROR: Missing or invalid dates.

RAW DATA:
Include this raw task data for reference at the end of your processing (do not modify): {TASK_DATA}`,

  phaseDelayAdvisor: `You are an HR assistant AI. Inputs available as placeholders: {{employeeName}}, {{taskTitle}}, {{phaseTitle}}, {{delayCategory}}, {{delayPercent}}, {{dueDate}}.

TASK:
- Generate a short notification message for the employee explaining the delay.
- Suggest one clear corrective action to avoid future delays.
- If delayCategory equals "MAJOR" (case-insensitive), set escalation to true; otherwise set to false.

OUTPUT CONSTRAINTS:
- Return ONLY a valid JSON object with exactly these keys:
  {
    "employeeMessage": string,
    "actionItem": string,
    "escalation": true|false
  }
- "employeeMessage" should be 1–2 short sentences referencing the task and phase and the delay percent and new due date.
- "actionItem" should be one concise corrective action.
- Use double quotes. No extra fields, comments, or surrounding text.
Here are the inputs for reference: {TASK_DATA}`,

  classifyRejectionReason: `
Classify this mistake as SMALL or BIG:
SMALL = formatting, typos, file issues, minor UI fixes.
BIG = missing functionality, wrong approach, wrong logic, major rework.

Or you can give by you own understanding if not clear.

Return ONLY ONE WORD: SMALL or BIG.

Reason: "${reason}"`,

  classifyEmployeeRejection: `
You are an HR AI assisting task management.
Classify the employee's rejection reason into exactly one of these:

1. "VALID_OVERLOAD"     → Employee has too much work already
2. "VALID_UNSKILLED"    → Employee lacks required skills
3. "VALID_TIME"         → Deadline is too short or unrealistic
4. "VALID_PERSONAL"     → Personal or health emergency
5. "INVALID"            → Excuse is unreasonable or not justified

Return ONLY ONE WORD from above. No explanation.

Reason Provided: "{reason}"
`
};